[project]
name = "visualization"
version = "1.0.0"
description = "Generate plots from benchmark data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "seaborn>=0.13.2",
]
